name: SamsungKernel

on:
  workflow_dispatch:
    inputs:
      device:
          description: 'device codename (e.g topaz/tissot)'
          default: 'samsung'
          required: true
      repo:
          description: 'Kernel source link (dont include . git at the end)'
          default: 'https://github.com/malkist01/android_kernel_samsung_msm8917.git'
          required: true
      branch:
          description: 'Kernel source branch'
          default: 'los18'
          required: true
      config:
          description: 'Defconfig'
          default: 'teletubies_defconfig'
          required: true
      token:
          description: 'Telegram bot token'
          default: '7596553794:AAGoeg4VypmUfBqfUML5VWt5mjivN5-3ah8'
          required: false
      chat_id:
          description: 'Telegram chat id'
          default: '-1002287610863'
          required: false


env:
  TZ: Asia/Jakarta
  DEVICE: ${{ github.event.inputs.device }}
  REPO: ${{ github.event.inputs.repo }}
  BRANCH: ${{ github.event.inputs.branch }}
  GKI: ${{ github.event.inputs.gki }}
  token: ${{ github.event.inputs.token }}
  chat_id: ${{ github.event.inputs.chat_id }}

jobs:
  kernel-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Initializing environment
        run: |
          git config --global user.name "malkist01"
          git config --global user.email "aripujiyanto0812@gmail.com"
          df -h
          ld --version
          gcc -v
          ar --version
          sudo apt update
          sudo apt install -y bc bison build-essential ccache curl flex glibc-source g++-multilib gcc-multilib binutils-aarch64-linux-gnu git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python2 tmate ssh neofetch
          neofetch

      - name: Compiling
        run: |
          if [ "${DEVICE}" = "samsung" ]; then
            wget https://raw.githubusercontent.com/malkist01/kernel_build_action/main/scripts/samsung.sh
            bash samsung.sh
          else
            echo "Device not supported yet"
          fi

